
USE DATABASE EGYPT_REAL_ESTATE_DB;

-- CREATE THE WAREHOUSE
CREATE OR REPLACE WAREHOUSE EGYPT_REAL_ESTATE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- CREATE THE EGYPT_REAL_ESTATE_DB
CREATE OR REPLACE DATABASE EGYPT_REAL_ESTATE_DB;

-- CREATE THE SCHEMAS
CREATE OR REPLACE SCHEMA raw_data;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA snapshots;
CREATE OR REPLACE SCHEMA analtycal_data;