 
-- view the current region 
SELECT Lower (CURRENT_REGION());

-- view the current account
SELECT Lower (CURRENT_ACCOUNT());

-- view the current user
SELECT CURRENT_USER();

-- Create a new user for the db and dwh
CREATE USER amin PASSWORD = '****'
LOGIN_NAME = 'amin'
DEFAULT_ROLE = ACCOUNTADMIN
MUST_CHANGE_PASSWORD = FALSE;

-- Grant admin role to user
GRANT ROLE ACCOUNTADMIN TO USER amin;

-- Grant access to the database
GRANT USAGE ON DATABASE EGYPT_REAL_ESTATE_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA EGYPT_REAL_ESTATE_DB.raw_data TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA EGYPT_REAL_ESTATE_DB.STAGING TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA EGYPT_REAL_ESTATE_DB.snapshots TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA EGYPT_REAL_ESTATE_DB.analtycal_data TO ROLE ACCOUNTADMIN;

-- Grant access to the DWH & Schemas
GRANT USAGE ON WAREHOUSE EGYPT_REAL_ESTATE_WH TO ROLE ACCOUNTADMIN ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EGYPT_REAL_ESTATE_DB.raw_data TO ROLE ACCOUNTADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EGYPT_REAL_ESTATE_DB.STAGING TO ROLE ACCOUNTADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EGYPT_REAL_ESTATE_DB.snapshots TO ROLE ACCOUNTADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EGYPT_REAL_ESTATE_DB.analtycal_data TO ROLE ACCOUNTADMIN;
