version: 2

sources:
  - name: RAW_DATA
    database: EGYPT_REAL_ESTATE_DB
    schema: RAW_DATA
    tables:
      - name: agent
      - name: lead
      - name: marketing_campaign
      - name: properties 
      - name: transactions
