version: 2 

models: 
    - name: stg_agents 
      description: working agents  
      columns:
        - name: agent_id
          description: ID of the table
          data_tests:
            - not_null
            - unique